M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date 18.12.2023 (пн) 16:27:55
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-18T16:27:55+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
%
G90
G05
T1
X21.91Y49.47
X27.69Y49.47
T0
M30
